---
- name: Restart Apache server
  hosts: all
  tasks:
    - name: Restart Apache2 service
      ansible.builtin.service:
        name: apache2  # Use "httpd" for RHEL/CentOS
        state: restarted
